import { readFile, writeFile } from 'node:fs/promises';
import { isAbsolute, resolve } from 'node:path';
import { Command } from 'commander';
import { output } from '../ui/output.js';

type ReplayBundle = {
  version: string;
  scenarioName: string;
  seed: number;
  mode: string;
  actions: Array<{
    tick: number;
    agentId: string;
    action: { name: string; params: Record<string, unknown> } | null;
  }>;
};

export const extractAgentCommand = new Command('extract-agent')
  .description('Extract a deterministic ActionSequenceAgent from a replay_bundle.json')
  .argument('<replayBundle>', 'Path to replay_bundle.json')
  .option('--agent-id <id>', 'Agent ID to extract (default: first agent in bundle)')
  .option('-o, --output <path>', 'Output file path', 'sim/generated/ExtractedAgent.ts')
  .action(async (replayBundlePath, options) => {
    try {
      const bundlePath = isAbsolute(replayBundlePath)
        ? replayBundlePath
        : resolve(process.cwd(), replayBundlePath);
      const raw = await readFile(bundlePath, 'utf8');
      const bundle = JSON.parse(raw) as ReplayBundle;

      const agentIds = Array.from(new Set(bundle.actions.map((a) => a.agentId)));
      const agentId = (options.agentId as string | undefined) ?? agentIds[0];
      if (!agentId) {
        throw new Error('No agentId found in replay bundle');
      }

      const extracted = bundle.actions
        .filter((a) => a.agentId === agentId && a.action)
        .map((a) => ({
          tick: a.tick,
          name: a.action!.name,
          params: a.action!.params ?? {},
        }));

      const outPath = isAbsolute(options.output)
        ? options.output
        : resolve(process.cwd(), options.output);

      const file = renderExtractedAgent({
        scenarioName: bundle.scenarioName,
        sourceAgentId: agentId,
        sequence: extracted,
      });

      await writeFile(outPath, file);
      output.success(`Extracted agent written to: ${outPath}`);
      output.newline();
      output.info(`Extracted ${extracted.length} actions for agentId=${agentId}`);
      process.exit(0);
    } catch (error) {
      output.error(`Failed to extract agent: ${error instanceof Error ? error.message : error}`);
      process.exit(2);
    }
  });

function renderExtractedAgent(input: {
  scenarioName: string;
  sourceAgentId: string;
  sequence: Array<{ tick: number; name: string; params: Record<string, unknown> }>;
}): string {
  const seqJson = JSON.stringify(
    input.sequence,
    (_k, v) => (typeof v === 'bigint' ? v.toString() : v),
    2
  );
  return `/**
 * Auto-generated by forge-sim extract-agent
 *
 * Source:
 * - scenario: ${input.scenarioName}
 * - agentId: ${input.sourceAgentId}
 */

import { ActionSequenceAgent } from '@elata-biosciences/agentforge';

export class ExtractedAgent extends ActionSequenceAgent {
  constructor(id: string) {
    super(id, { sequence: ${seqJson} });
  }
}
`;
}
